import {JSX} from 'react';
import LegalPage from './LegalPage';
import {useLang} from "../../state/lang-state";

function EnglishContent(): JSX.Element {
    return (
        <>
            <h2>1. What We Collect</h2>
            <ul>
                <li>Account details you provide when registering (first name, last name, email, gender).</li>
                <li>Questions you type in and readings you choose to save.</li>
                <li>Language preference and in-progress spread state, kept in your browser's local storage.</li>
            </ul>

            <h2>2. How We Use It</h2>
            <p>We use this information to run the App: to generate and translate your readings, let you save and revisit them, and remember your preferences between visits. We don't sell your data or use it for advertising.</p>

            <h2>3. Third-Party Services</h2>
            <p>Reading interpretations, translations, and follow-up answers are generated by sending your question and drawn cards to a third-party AI provider (OpenAI). Please avoid including sensitive personal information in your questions.</p>

            <h2>4. Local Storage</h2>
            <p>The App uses your browser's local storage — not tracking cookies — to remember things like your current spread, language, and whether you've seen the reading notice. This stays on your device and isn't shared with us.</p>

            <h2>5. Data Retention & Deletion</h2>
            <p>Saved readings remain in your account until you delete them from "My Spreads." To request full account deletion, reach out through the contact details available on the App.</p>

            <h2>6. Children's Privacy</h2>
            <p>The App isn't directed at children, and we don't knowingly collect information from anyone under 16.</p>

            <h2>7. Changes</h2>
            <p>We may update this Privacy Policy from time to time. Continuing to use the App after a change means you accept the updated policy.</p>

            <h2>8. Contact</h2>
            <p>Questions about this policy can be sent through the contact details available on the App.</p>
        </>
    );
}

function HebrewContent(): JSX.Element {
    return (
        <>
            <h2>1. המידע שאנו אוספים</h2>
            <ul>
                <li>פרטי חשבון הנמסרים בעת ההרשמה: שם פרטי, שם משפחה, כתובת דוא"ל ומגדר.</li>
                <li>שאלות שאתם מקלידים ופריסות שאתם בוחרים לשמור.</li>
                <li>העדפת שפה ומצב הפריסה הפעילה, הנשמרים באחסון המקומי (local storage) של הדפדפן.</li>
            </ul>

            <h2>2. כיצד אנו עושים שימוש במידע</h2>
            <p>המידע משמש להפעלת האפליקציה: יצירת הקריאות ותרגומן, מתן אפשרות לשמור אותן ולחזור אליהן, וזכירת ההעדפות שלכם בין ביקור לביקור. איננו מוכרים את המידע שלכם ואיננו עושים בו שימוש לצורכי פרסום.</p>

            <h2>3. שירותי צד שלישי</h2>
            <p>פירוש הפריסות, תרגומן ומענה לשאלות המשך מופקים על ידי שליחת השאלה שהוזנה והקלפים שנשלפו לספק בינה מלאכותית חיצוני (OpenAI). מומלץ להימנע מהכללת מידע אישי רגיש בשאלות שלכם.</p>

            <h2>4. אחסון מקומי</h2>
            <p>האפליקציה משתמשת באחסון המקומי של הדפדפן — ולא בעוגיות מעקב — כדי לזכור פרטים כגון הפריסה הנוכחית, שפת התצוגה, והאם כבר צפיתם בהודעת הקריאה. מידע זה נשמר על גבי המכשיר שלכם בלבד ואינו מועבר אלינו.</p>

            <h2>5. שמירת מידע ומחיקתו</h2>
            <p>פריסות שמורות נותרות בחשבונכם עד למחיקתן דרך עמוד "הפריסות שלי". לבקשת מחיקה מלאה של החשבון, ניתן לפנות דרך פרטי הקשר המופיעים באפליקציה.</p>

            <h2>6. פרטיות קטינים</h2>
            <p>האפליקציה אינה מיועדת לילדים, ואיננו אוספים ביודעין מידע מאנשים מתחת לגיל 16.</p>

            <h2>7. שינויים במדיניות</h2>
            <p>מדיניות פרטיות זו עשויה להתעדכן מעת לעת. המשך השימוש באפליקציה לאחר פרסום עדכון מהווה הסכמה למדיניות המעודכנת.</p>

            <h2>8. יצירת קשר</h2>
            <p>לשאלות בנוגע למדיניות זו, ניתן לפנות דרך פרטי הקשר המופיעים באפליקציה.</p>
        </>
    );
}

function PrivacyPage(): JSX.Element {
    const lang = useLang();
    return (
        <LegalPage titleKey="footerPrivacy">
            {lang === 'he' ? <HebrewContent /> : <EnglishContent />}
        </LegalPage>
    );
}

export default PrivacyPage;
